### ISSUE TITLE
Stale comment in Getting Started

### ISSUE THREAD

**Issue by pmrcunha** [tokio-rs/website#369]
Hi!
I went through the Getting started section of the docs today, and noticed a stale comment in the echo server example:
https://github.com/tokio-rs/website/blame/master/content/docs/getting-started/echo.md#L67

It can cause some confusion so it might be better to update or remove it.

**Comment by tones111** [comment]
I just came across this too.  I was confused because the comment talks about using for_each but the code is using a while let pattern.

Also, the link to tokio::spawn takes you to a page that says "The requested resource does not exist"

[https://github.com/tokio-rs/website/blame/master/content/docs/getting-started/echo.md#L56](https://github.com/tokio-rs/website/blame/master/content/docs/getting-started/echo.md#L56)

**Comment by ultrasaurus** [comment]
I'm working on doing a sweep through the guide and will make sure these are fixed -- thanks for the feedback!
