### ISSUE TITLE
concepts that should have common vocabulary

### ISSUE THREAD

**Issue by ultrasaurus** [tokio-rs/website#400]
We have many awesome people helping with the guides.  For consistency across different
parts of the docs (and also because clarifying our language can help clarify our thinking), we'd like to track what concepts would benefit from common vocabulary.

via @jebrosen 
> "blocking" means a lot of things to different people. IIUC that hello world syscall-blocks (epoll) at each await because it's the only task and there are no timers or anything else. Any future or task "blocks" at every await point from the task's perspective, but that may or may not block a thread because there might be other work
I've seen discussions on Reddit where people use different meanings or kinds of blocking interchangeably or with a different meaning from the post they replied to

maybe more words will help(e.g. blocked system call, blocked task, blocked program execution)

via @carllerche 
> I never know what to call it when a future / .await completes does it return a value, emit, yield, ...?

**Comment by Darksonn** [comment]
My five cents:

**Blocking**: When talking about blocking, we should perhaps be more explicit about _what_ is blocked. For example calling await will block the future, but not the thread. And make this distinction clear from the beginning.

You mention a "blocked system call", but I would say that it isn't the systemcall that's blocked — the system call blocks the thread.

**Future completion**: I'm personally a fan of the expression "completes to", e.g. the future completes to an integer. I don't like emit or yield, because futures only "return" once, and yield sounds like a generator returning possibly many items.

**Comment by ultrasaurus** [comment]
Tasks...

via @carllerche 
> a task is usually what you get when you call task::spawn
> It is roughly the tokio equivalent to a thread and the equivalent to a goroutine or an erlang process

whereas [std::task](https://doc.rust-lang.org/std/task/index.html) is part of the waker system, not an actual task impl

**Comment by jebrosen** [comment]
I feel silly for only remembering now, but I started https://www.jebrosen.com/static/rust-async-dictionary.html a while back and never got around to submitting it anywhere. I would love to expand/correct/publish it, maybe as part of these efforts.

**Comment by hawkw** [comment]
> maybe more words will help(e.g. blocked system call, blocked task, blocked program execution)

In writing tokio's RustDoc API docs, I have used the terms "is pending" and "yields" rather than "is blocked" or "blocks" to describe tasks. I think we should try to keep website docs and API docs using consistent terminology as well (even if this means changing the lib docs!).



> Tasks...
> 
> via @carllerche
> 
> > a task is usually what you get when you call task::spawn
> > It is roughly the tokio equivalent to a thread and the equivalent to a goroutine or an erlang process
> 
> whereas [std::task](https://doc.rust-lang.org/std/task/index.html)
> 
> > is part of the waker system, not an actual task impl.  you only need to know about that module if you are implementing `Future` by hand

In Tokio's API docs, we definitely [discuss "tasks" as something that users should care about](https://docs.rs/tokio/0.2.9/tokio/task/index.html#what-are-tasks). A framing I like about the future/task distinction (which hasn't actually made it into the API docs yet...) is that a "future" refers to a task "at rest", while a "task" refers to a future "in flight" (or "in motion"). By that I mean that I think about a "future" as being a Rust type that _defines_ an asynchronous unit of work, while a "task" is an asynchronous unit of work that is being run by an executor.

Anyway, just my 2¢. Hopefully some of that is useful?

**Comment by ultrasaurus** [comment]
here's another example in context https://github.com/tokio-rs/tokio/commit/a28490e6b5e99ae8d564e128136edb6007743a18 -- I think this is a good use of "yeild" instead of "block" by @hawkw

**Comment by Darksonn** [comment]
The new website has [a glossary][1] now. Are there any concepts there that are still missing?

[1]: https://tokio.rs/tokio/glossary

**Comment by carllerche** [comment]
I'm going to close this. We have a glossary now and the content is all rewritten. What we probably should do in the future when we hit "lingo" is to add them to glossary and link it.
